### PR TITLE
(fix) Ticker/TickerList: changing for showing long pairs

### PR DESCRIPTION
**Pull request by dmytroshch**
## Prerequisites
N/A

## Task reference
https://app.asana.com/0/1189676765887416/1200429717068474
https://bitfinex.slack.com/archives/CKKLH6HA9/p1623162407259300

## BREAKING CHANGES
N/A

## PR description
1. Ticker: if length of quote+base ccy is bigger than 10, base ccy is smaller sized
2. TickerList: breaking the line on "/" symbol

## Example app screenshot
Снимок экрана от 2021-06-08 17-34-48
Снимок экрана от 2021-06-08 17-29-06
Снимок экрана от 2021-06-10 11-14-18

(Add example app screenshot if applicable, otherwise put "N/A")

## Storybook screenshot
N/A

## Checklist
  - [x] PR title has category name prefix, e.g. "\(fix\) {description}" (fix/feature/refactor/improvement/doc/test)
  - [x] Added PR description
  - [x] Relevant change in example app is verified, added example app screenshot
  - [x] Storybook: stories, docs are updated/verified
  - [x] `Pull request verify workflow` passed
  - [x] PR development is completed, the developer is satisfied with the code quality and behavior of the app

### CODE REVIEW

**Review by bhoomij — CHANGES_REQUESTED** [review]
looks good, could you add ufx-ui/example screenshot please ?

**Comment by bhoomij** [comment]
> Currently the table head and body are in different tables:
> image
> 
> Can we combine them so that the cells have consistent widths?

If we plan to combine them, please see that when scrolling vertically table-headers are fixed at top and only table-body is scrollable

**Comment by JasonMHasperhoven** [comment]
> > Currently the table head and body are in different tables:
> > Can we combine them so that the cells have consistent widths?
> 
> If we plan to combine them, please see that when scrolling vertically table-headers are fixed at top and only table-body is scrollable

Ah I see that's why it's separate. We have to make sure the column widths are matching then.

**Review by bhoomij — CHANGES_REQUESTED** [review]
we should handle following: 
- for ufx-ui/example screenshot, it has enough space, so its not good to still show it in small size when there is enough room in between
- ideally last-price and name should have same font-size, can take input from design team

we should explore other ways, please see if after new ticker styles ([PR-56](https://github.com/bitfinexcom/ufx-ui/pull/56), we get enough space for long-names
we could reduce font-size and have min-width for ticker component and user cant resize lesser than that min-width

**Pull request closed without merging**
